version: '3.8'
services:
  react_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./build:/var/www
      - ./etc/:/etc/nginx/conf.d/
    depends_on:
      - react_app
