FROM node:lts-alpine as builder

WORKDIR /app
COPY package.json .

RUN npm install


COPY . .
RUN npm run build






FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html



FROM node:16-alpine AS builder

WORKDIR /app

COPY package.json ./

COPY package-lock.json ./

RUN npm install

COPY . .

RUN npm run build









FROM nginx:1.19-alpine AS server

COPY ./etc/nginx.conf /etc/nginx/conf.d/default.conf

RUN apk update \
	&& apk upgrade \
	&& apk add --no-cache openssl \
	&& apk add --no-cache certbot

COPY --from=builder ./app/build /usr/share/nginx/html

EXPOSE 80
